### ISSUE TITLE
Hands on

### ISSUE THREAD

**Issue by roshan2004** [plumed/lugano2019#1]
Since the hands-on data is available, looking forward to the hands-on tutorial as well.
Thanks

**Comment by carlocamilloni** [comment]
hands on tutorial are available in the plumed manual https://www.plumed.org/doc-v2.5/user-doc/html/index.html

**Comment by Paulie-ai** [comment]
Bugs in Lugano tutorial: Dimensionality reduction
Recently i try to make PCA and MDS part  following tutorial, but when perform it show :
"
+++ message follows +++
ERROR
I cannot understand line: CLASSICAL_MDS LABEL=mds USE_OUTPUT_DATA_FROM=fps NLOW_DIM=2
Maybe a missing space or a typo?
"
My plumed input file is as same as ./solutions, i using plumed2.6.6 and check input times. 
Could you find the error anywhere ?

**Comment by gtribello** [comment]
I think you have not complied with the dimred module enabled?  When you configure, you need to do:

configure --enable-modules all

or you need to download PLUMED from conda as the exercise tells you.  I tested all these inputs recently.  See:

https://plumed-school.github.io/lessons/21/006/data/DIMENSIONALITY.html

All the inputs are parsed correctly.

**Comment by Paulie-ai** [comment]
Thanks for your reply, i realized that problem， should i complied the plumed again?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plumed/lugano2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 晚上11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plumed/lugano2019] Hands on (#1)





 
I think you have not complied with the dimred module enabled?  When you configure, you need to do:
 
configure --enable-modules all
 
or you need to download PLUMED from conda as the exercise tells you.  I tested all these inputs recently.  See:
 
https://plumed-school.github.io/lessons/21/006/data/DIMENSIONALITY.html
 
All the inputs are parsed correctly.
