### ISSUE TITLE
Inconsistency in link description n content 

### ISSUE THREAD

**Issue by fireballpoint1** [plumed/lugano2019#2]
The tutorial [here](https://www.plumed.org/doc-v2.5/user-doc/html/lugano-6a.html) uses [tarball](https://www.plumed.org/doc-v2.5/user-doc/html/tutorial-resources/lugano-4.tar.gz) which is supposed to have 
> lammps-equilibration.in : The input for LAMMPS that we will use for our setup and equilibration steps of our investigation
lammps-production.in : The input for LAMMPS that will be used for the production steps of our investigation
xdistances.dat : A PLUMED file that defines the collective variables that we will use in the investigation. We will include this file in the PLUMED input files we write for this tutorial.
This tutorial has been tested on v2.5 but it should also work with other versions of PLUMED.

However, the contents are quite different with no plumed fix in the only lammps input file.

**Comment by gtribello** [comment]
OK that should be fixed now.  The link I had included was to the wrong file.  Sorry about that.
